/**
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.btsdsl.serializer;

import org.bbaw.bts.corpus.text.btsdsl.serializer.AbstractBTSSemanticSequencer;

@SuppressWarnings("all")
public class BTSSemanticSequencer extends AbstractBTSSemanticSequencer {
}
