/**
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.btsdsl.serializer;

@SuppressWarnings("all")
public class BTSSemanticSequencer /* implements AbstractBTSSemanticSequencer  */{
}
