/*
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.egy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EgyDslRuntimeModule extends org.bbaw.bts.corpus.text.egy.AbstractEgyDslRuntimeModule {

}
