/**
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.btsdsl.ui.contentassist;

import org.bbaw.bts.corpus.text.btsdsl.ui.contentassist.AbstractBTSProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class BTSProposalProvider extends AbstractBTSProposalProvider {
}
