/*
* generated by Xtext
*/
package org.bbaw.bts.corpus.text.btsdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BTSStandaloneSetup extends BTSStandaloneSetupGenerated{

	public static void doSetup() {
		new BTSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

