<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="btsCorpusModel" nsURI="http://btsCorpusModel/1.0" nsPrefix="btsCorpusModel">
  <eClassifiers xsi:type="ecore:EClass" name="BTSCorpusObject" abstract="true" eSuperTypes="../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="passport" eType="#//BTSPassport"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="corpusPrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workPhase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSTCObject" eSuperTypes="#//BTSCorpusObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="BTSText" eSuperTypes="#//BTSCorpusObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textContent" eType="#//BTSTextContent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSLemmaEntry" eSuperTypes="#//BTSCorpusObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="words" upperBound="-1"
        eType="#//BTSWord" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translations" eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTranslations"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSPassport">
    <eOperations name="getPassportEntryByPath" eType="#//BTSPassportEntry">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getPassportEntryStringValueByPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="date" eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTimespan"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//BTSPassportEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
        eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTranslations"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSAnnotation" eSuperTypes="#//BTSCorpusObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="BTSPassportEntryGroup" eSuperTypes="#//BTSPassportEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//BTSPassportEntryItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSTextCorpus" eSuperTypes="#//BTSCorpusObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//BTSCorpusHeader"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSImage" eSuperTypes="#//BTSCorpusObject">
    <eOperations name="getAttachement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSCorpusHeader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSThsEntry" eSuperTypes="#//BTSCorpusObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="BTSTextContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textItems" upperBound="-1"
        eType="#//BTSTextItems" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSPassportEntry" abstract="true" eSuperTypes="../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSIdentifiableItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//BTSPassportEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTranslations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSWord" eSuperTypes="#//BTSAmbivalenceItem #//BTSSentenceItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="translation" eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTranslations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flexCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wChar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphics" upperBound="-1"
        eType="#//BTSGraphic" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSTextItems" abstract="true" interface="true"
      eSuperTypes="../../org.bbaw.bts.model/model/BTSModel.ecore#//AdministrativDataObject ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSNamedTypedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="BTSGraphic" eSuperTypes="../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSIdentifiableItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="innerSentenceOrder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignored" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSSenctence" eSuperTypes="#//BTSTextItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentenceItems" upperBound="-1"
        eType="#//BTSSentenceItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translation" eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTranslations"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSMarker" eSuperTypes="#//BTSAmbivalenceItem #//BTSTextSentenceItem #//BTSTextItems #//BTSSentenceItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSSentenceItem" abstract="true" interface="true"
      eSuperTypes="../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSNamedTypedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="BTSAmbivalence" eSuperTypes="#//BTSTextSentenceItem #//BTSTextItems #//BTSSentenceItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//BTSLemmaCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSLemmaCase" eSuperTypes="../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSNamedTypedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" upperBound="-1"
        eType="#//BTSAmbivalenceItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSTextSentenceItem" abstract="true"
      eSuperTypes="#//BTSSentenceItem #//BTSTextItems"/>
  <eClassifiers xsi:type="ecore:EClass" name="BTSAmbivalenceItem" abstract="true"
      interface="true" eSuperTypes="../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSIdentifiableItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="BTSPassportEntryItem" eSuperTypes="#//BTSPassportEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalReferences" upperBound="-1"
        eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSExternalReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timespan" eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTimespan"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTranslations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translation" eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSTranslations"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSAbstractText" eSuperTypes="#//BTSCorpusObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraphs" upperBound="-1"
        eType="#//BTSAbstractParagraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BTSAbstractParagraph" eSuperTypes="../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSIdentifiableItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="witnesses" upperBound="-1"
        eType="ecore:EClass ../../org.bbaw.bts.model/model/BTSModel.ecore#//BTSRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
