/*
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.egy.dsl.ui.contentassist

import org.bbaw.bts.corpus.text.egy.dsl.ui.contentassist.AbstractEgyBtsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EgyBtsProposalProvider extends AbstractEgyBtsProposalProvider {
}
