/**
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.btsdsl.ui.outline;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class BTSOutlineTreeProvider /* implements org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider  */{
}
