/*
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.btsdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BTSUiModule extends org.bbaw.bts.corpus.text.btsdsl.ui.AbstractBTSUiModule {
	public BTSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
