/*
* generated by Xtext
*/
package org.bbaw.bts.corpus.text.egy.dsl.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractEgyBtsJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.bbaw.bts.corpus.text.egy.dsl.egyBts.EgyBtsPackage.eINSTANCE);
		return result;
	}

}
