/**
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.btsdsl.formatting;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
@SuppressWarnings("all")
public class BTSFormatter extends AbstractDeclarativeFormatter {
  @Inject
  @Extension
  private /* BTSGrammarAccess */Object _bTSGrammarAccess;
  
  @Override
  protected void configureFormatting(final FormattingConfig c) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method findKeywordPairs(String, String) is undefined"
      + "\nThe method findKeywords(String) is undefined"
      + "\nThe method or field SL_COMMENTRule is undefined"
      + "\nThe method or field ML_COMMENTRule is undefined"
      + "\nThe method or field ML_COMMENTRule is undefined"
      + "\nfirst cannot be resolved"
      + "\nsecond cannot be resolved"
      + "\nfirst cannot be resolved"
      + "\nsecond cannot be resolved"
      + "\nsecond cannot be resolved");
  }
}
