/*
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.egy.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EgyBtsUiModule extends org.bbaw.bts.corpus.text.egy.dsl.ui.AbstractEgyBtsUiModule {
	public EgyBtsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
