/*
* generated by Xtext
*/
package org.bbaw.bts.corpus.text.btsdsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class BTSGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class BTSTextContentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSTextContent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSTextContentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSTextContentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTextItemsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cTextItemsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cTextItemsBTSTextItemsParserRuleCall_3_2_0 = (RuleCall)cTextItemsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cTextItemsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cTextItemsBTSTextItemsParserRuleCall_3_3_1_0 = (RuleCall)cTextItemsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//BTSTextContent:
		//	{BTSTextContent} "BTSTextContent" "{" ("textItems" "{" textItems+=BTSTextItems ("," textItems+=BTSTextItems)* "}")?
		//	"}";
		public ParserRule getRule() { return rule; }

		//{BTSTextContent} "BTSTextContent" "{" ("textItems" "{" textItems+=BTSTextItems ("," textItems+=BTSTextItems)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{BTSTextContent}
		public Action getBTSTextContentAction_0() { return cBTSTextContentAction_0; }

		//"BTSTextContent"
		public Keyword getBTSTextContentKeyword_1() { return cBTSTextContentKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("textItems" "{" textItems+=BTSTextItems ("," textItems+=BTSTextItems)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"textItems"
		public Keyword getTextItemsKeyword_3_0() { return cTextItemsKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//textItems+=BTSTextItems
		public Assignment getTextItemsAssignment_3_2() { return cTextItemsAssignment_3_2; }

		//BTSTextItems
		public RuleCall getTextItemsBTSTextItemsParserRuleCall_3_2_0() { return cTextItemsBTSTextItemsParserRuleCall_3_2_0; }

		//("," textItems+=BTSTextItems)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//textItems+=BTSTextItems
		public Assignment getTextItemsAssignment_3_3_1() { return cTextItemsAssignment_3_3_1; }

		//BTSTextItems
		public RuleCall getTextItemsBTSTextItemsParserRuleCall_3_3_1_0() { return cTextItemsBTSTextItemsParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class BTSSentenceItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSSentenceItem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBTSWordParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBTSMarkerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBTSAmbivalenceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//BTSSentenceItem:
		//	BTSWord | BTSMarker | BTSAmbivalence;
		public ParserRule getRule() { return rule; }

		//BTSWord | BTSMarker | BTSAmbivalence
		public Alternatives getAlternatives() { return cAlternatives; }

		//BTSWord
		public RuleCall getBTSWordParserRuleCall_0() { return cBTSWordParserRuleCall_0; }

		//BTSMarker
		public RuleCall getBTSMarkerParserRuleCall_1() { return cBTSMarkerParserRuleCall_1; }

		//BTSAmbivalence
		public RuleCall getBTSAmbivalenceParserRuleCall_2() { return cBTSAmbivalenceParserRuleCall_2; }
	}

	public class BTSAmbivalenceItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSAmbivalenceItem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBTSWordParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBTSMarkerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//BTSAmbivalenceItem:
		//	BTSWord | BTSMarker;
		public ParserRule getRule() { return rule; }

		//BTSWord | BTSMarker
		public Alternatives getAlternatives() { return cAlternatives; }

		//BTSWord
		public RuleCall getBTSWordParserRuleCall_0() { return cBTSWordParserRuleCall_0; }

		//BTSMarker
		public RuleCall getBTSMarkerParserRuleCall_1() { return cBTSMarkerParserRuleCall_1; }
	}

	public class BTSTextItemsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSTextItems");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBTSSenctenceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBTSMarkerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBTSAmbivalenceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//BTSTextItems:
		//	BTSSenctence | BTSMarker | BTSAmbivalence;
		public ParserRule getRule() { return rule; }

		//BTSSenctence | BTSMarker | BTSAmbivalence
		public Alternatives getAlternatives() { return cAlternatives; }

		//BTSSenctence
		public RuleCall getBTSSenctenceParserRuleCall_0() { return cBTSSenctenceParserRuleCall_0; }

		//BTSMarker
		public RuleCall getBTSMarkerParserRuleCall_1() { return cBTSMarkerParserRuleCall_1; }

		//BTSAmbivalence
		public RuleCall getBTSAmbivalenceParserRuleCall_2() { return cBTSAmbivalenceParserRuleCall_2; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class BTSSenctenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSSenctence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSSenctenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSSenctenceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStateEStringParserRuleCall_4_1_0 = (RuleCall)cStateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRevisionStateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRevisionStateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRevisionStateEStringParserRuleCall_5_1_0 = (RuleCall)cRevisionStateAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cVisibilityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cVisibilityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cVisibilityEStringParserRuleCall_6_1_0 = (RuleCall)cVisibilityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSortKeyKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSortKeyAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSortKeyEIntParserRuleCall_7_1_0 = (RuleCall)cSortKeyAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cTypeKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cTypeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_8_1_0 = (RuleCall)cTypeAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSubtypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cSubtypeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cSubtypeEStringParserRuleCall_9_1_0 = (RuleCall)cSubtypeAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCodeKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCodeAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_10_1_0 = (RuleCall)cCodeAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword c_idKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment c_idAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall c_idEStringParserRuleCall_11_1_0 = (RuleCall)c_idAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommentKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cCommentAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cCommentEStringParserRuleCall_12_1_0 = (RuleCall)cCommentAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cParentIdKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cParentIdAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cParentIdEStringParserRuleCall_13_1_0 = (RuleCall)cParentIdAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cSentenceItemsKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cSentenceItemsAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final RuleCall cSentenceItemsBTSSentenceItemParserRuleCall_14_2_0 = (RuleCall)cSentenceItemsAssignment_14_2.eContents().get(0);
		private final Group cGroup_14_3 = (Group)cGroup_14.eContents().get(3);
		private final Keyword cCommaKeyword_14_3_0 = (Keyword)cGroup_14_3.eContents().get(0);
		private final Assignment cSentenceItemsAssignment_14_3_1 = (Assignment)cGroup_14_3.eContents().get(1);
		private final RuleCall cSentenceItemsBTSSentenceItemParserRuleCall_14_3_1_0 = (RuleCall)cSentenceItemsAssignment_14_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14_4 = (Keyword)cGroup_14.eContents().get(4);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cTranslationKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cTranslationAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cTranslationBTSTranslationsParserRuleCall_15_1_0 = (RuleCall)cTranslationAssignment_15_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//BTSSenctence:
		//	{BTSSenctence} "BTSSenctence" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
		//	("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
		//	("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)?
		//	("sentenceItems" "{" sentenceItems+=BTSSentenceItem ("," sentenceItems+=BTSSentenceItem)* "}")? ("translation"
		//	translation=BTSTranslations)? "}";
		public ParserRule getRule() { return rule; }

		//{BTSSenctence} "BTSSenctence" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
		//("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
		//("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)?
		//("sentenceItems" "{" sentenceItems+=BTSSentenceItem ("," sentenceItems+=BTSSentenceItem)* "}")? ("translation"
		//translation=BTSTranslations)? "}"
		public Group getGroup() { return cGroup; }

		//{BTSSenctence}
		public Action getBTSSenctenceAction_0() { return cBTSSenctenceAction_0; }

		//"BTSSenctence"
		public Keyword getBTSSenctenceKeyword_1() { return cBTSSenctenceKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("state" state=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"state"
		public Keyword getStateKeyword_4_0() { return cStateKeyword_4_0; }

		//state=EString
		public Assignment getStateAssignment_4_1() { return cStateAssignment_4_1; }

		//EString
		public RuleCall getStateEStringParserRuleCall_4_1_0() { return cStateEStringParserRuleCall_4_1_0; }

		//("revisionState" revisionState=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"revisionState"
		public Keyword getRevisionStateKeyword_5_0() { return cRevisionStateKeyword_5_0; }

		//revisionState=EString
		public Assignment getRevisionStateAssignment_5_1() { return cRevisionStateAssignment_5_1; }

		//EString
		public RuleCall getRevisionStateEStringParserRuleCall_5_1_0() { return cRevisionStateEStringParserRuleCall_5_1_0; }

		//("visibility" visibility=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"visibility"
		public Keyword getVisibilityKeyword_6_0() { return cVisibilityKeyword_6_0; }

		//visibility=EString
		public Assignment getVisibilityAssignment_6_1() { return cVisibilityAssignment_6_1; }

		//EString
		public RuleCall getVisibilityEStringParserRuleCall_6_1_0() { return cVisibilityEStringParserRuleCall_6_1_0; }

		//("sortKey" sortKey=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"sortKey"
		public Keyword getSortKeyKeyword_7_0() { return cSortKeyKeyword_7_0; }

		//sortKey=EInt
		public Assignment getSortKeyAssignment_7_1() { return cSortKeyAssignment_7_1; }

		//EInt
		public RuleCall getSortKeyEIntParserRuleCall_7_1_0() { return cSortKeyEIntParserRuleCall_7_1_0; }

		//("type" type=EString)?
		public Group getGroup_8() { return cGroup_8; }

		//"type"
		public Keyword getTypeKeyword_8_0() { return cTypeKeyword_8_0; }

		//type=EString
		public Assignment getTypeAssignment_8_1() { return cTypeAssignment_8_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_8_1_0() { return cTypeEStringParserRuleCall_8_1_0; }

		//("subtype" subtype=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"subtype"
		public Keyword getSubtypeKeyword_9_0() { return cSubtypeKeyword_9_0; }

		//subtype=EString
		public Assignment getSubtypeAssignment_9_1() { return cSubtypeAssignment_9_1; }

		//EString
		public RuleCall getSubtypeEStringParserRuleCall_9_1_0() { return cSubtypeEStringParserRuleCall_9_1_0; }

		//("code" code=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"code"
		public Keyword getCodeKeyword_10_0() { return cCodeKeyword_10_0; }

		//code=EString
		public Assignment getCodeAssignment_10_1() { return cCodeAssignment_10_1; }

		//EString
		public RuleCall getCodeEStringParserRuleCall_10_1_0() { return cCodeEStringParserRuleCall_10_1_0; }

		//("_id" _id=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"_id"
		public Keyword get_idKeyword_11_0() { return c_idKeyword_11_0; }

		//_id=EString
		public Assignment get_idAssignment_11_1() { return c_idAssignment_11_1; }

		//EString
		public RuleCall get_idEStringParserRuleCall_11_1_0() { return c_idEStringParserRuleCall_11_1_0; }

		//("comment" comment=EString)?
		public Group getGroup_12() { return cGroup_12; }

		//"comment"
		public Keyword getCommentKeyword_12_0() { return cCommentKeyword_12_0; }

		//comment=EString
		public Assignment getCommentAssignment_12_1() { return cCommentAssignment_12_1; }

		//EString
		public RuleCall getCommentEStringParserRuleCall_12_1_0() { return cCommentEStringParserRuleCall_12_1_0; }

		//("parentId" parentId=EString)?
		public Group getGroup_13() { return cGroup_13; }

		//"parentId"
		public Keyword getParentIdKeyword_13_0() { return cParentIdKeyword_13_0; }

		//parentId=EString
		public Assignment getParentIdAssignment_13_1() { return cParentIdAssignment_13_1; }

		//EString
		public RuleCall getParentIdEStringParserRuleCall_13_1_0() { return cParentIdEStringParserRuleCall_13_1_0; }

		//("sentenceItems" "{" sentenceItems+=BTSSentenceItem ("," sentenceItems+=BTSSentenceItem)* "}")?
		public Group getGroup_14() { return cGroup_14; }

		//"sentenceItems"
		public Keyword getSentenceItemsKeyword_14_0() { return cSentenceItemsKeyword_14_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_14_1() { return cLeftCurlyBracketKeyword_14_1; }

		//sentenceItems+=BTSSentenceItem
		public Assignment getSentenceItemsAssignment_14_2() { return cSentenceItemsAssignment_14_2; }

		//BTSSentenceItem
		public RuleCall getSentenceItemsBTSSentenceItemParserRuleCall_14_2_0() { return cSentenceItemsBTSSentenceItemParserRuleCall_14_2_0; }

		//("," sentenceItems+=BTSSentenceItem)*
		public Group getGroup_14_3() { return cGroup_14_3; }

		//","
		public Keyword getCommaKeyword_14_3_0() { return cCommaKeyword_14_3_0; }

		//sentenceItems+=BTSSentenceItem
		public Assignment getSentenceItemsAssignment_14_3_1() { return cSentenceItemsAssignment_14_3_1; }

		//BTSSentenceItem
		public RuleCall getSentenceItemsBTSSentenceItemParserRuleCall_14_3_1_0() { return cSentenceItemsBTSSentenceItemParserRuleCall_14_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14_4() { return cRightCurlyBracketKeyword_14_4; }

		//("translation" translation=BTSTranslations)?
		public Group getGroup_15() { return cGroup_15; }

		//"translation"
		public Keyword getTranslationKeyword_15_0() { return cTranslationKeyword_15_0; }

		//translation=BTSTranslations
		public Assignment getTranslationAssignment_15_1() { return cTranslationAssignment_15_1; }

		//BTSTranslations
		public RuleCall getTranslationBTSTranslationsParserRuleCall_15_1_0() { return cTranslationBTSTranslationsParserRuleCall_15_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}

	public class BTSWordElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSWord");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSWordAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSWordKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStateEStringParserRuleCall_4_1_0 = (RuleCall)cStateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRevisionStateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRevisionStateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRevisionStateEStringParserRuleCall_5_1_0 = (RuleCall)cRevisionStateAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cVisibilityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cVisibilityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cVisibilityEStringParserRuleCall_6_1_0 = (RuleCall)cVisibilityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSortKeyKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSortKeyAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSortKeyEIntParserRuleCall_7_1_0 = (RuleCall)cSortKeyAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cTypeKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cTypeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_8_1_0 = (RuleCall)cTypeAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSubtypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cSubtypeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cSubtypeEStringParserRuleCall_9_1_0 = (RuleCall)cSubtypeAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCodeKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCodeAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_10_1_0 = (RuleCall)cCodeAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword c_idKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment c_idAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall c_idEStringParserRuleCall_11_1_0 = (RuleCall)c_idAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommentKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cCommentAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cCommentEStringParserRuleCall_12_1_0 = (RuleCall)cCommentAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cParentIdKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cParentIdAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cParentIdEStringParserRuleCall_13_1_0 = (RuleCall)cParentIdAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cWTypeKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cWTypeAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cWTypeEStringParserRuleCall_14_1_0 = (RuleCall)cWTypeAssignment_14_1.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cLTypeKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cLTypeAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cLTypeEStringParserRuleCall_15_1_0 = (RuleCall)cLTypeAssignment_15_1.eContents().get(0);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cLKeyKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Assignment cLKeyAssignment_16_1 = (Assignment)cGroup_16.eContents().get(1);
		private final RuleCall cLKeyEStringParserRuleCall_16_1_0 = (RuleCall)cLKeyAssignment_16_1.eContents().get(0);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cFlexCodeKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Assignment cFlexCodeAssignment_17_1 = (Assignment)cGroup_17.eContents().get(1);
		private final RuleCall cFlexCodeEStringParserRuleCall_17_1_0 = (RuleCall)cFlexCodeAssignment_17_1.eContents().get(0);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Keyword cWCharKeyword_18_0 = (Keyword)cGroup_18.eContents().get(0);
		private final Assignment cWCharAssignment_18_1 = (Assignment)cGroup_18.eContents().get(1);
		private final RuleCall cWCharEStringParserRuleCall_18_1_0 = (RuleCall)cWCharAssignment_18_1.eContents().get(0);
		private final Group cGroup_19 = (Group)cGroup.eContents().get(19);
		private final Keyword cValueKeyword_19_0 = (Keyword)cGroup_19.eContents().get(0);
		private final Assignment cValueAssignment_19_1 = (Assignment)cGroup_19.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_19_1_0 = (RuleCall)cValueAssignment_19_1.eContents().get(0);
		private final Group cGroup_20 = (Group)cGroup.eContents().get(20);
		private final Keyword cTranslationKeyword_20_0 = (Keyword)cGroup_20.eContents().get(0);
		private final Assignment cTranslationAssignment_20_1 = (Assignment)cGroup_20.eContents().get(1);
		private final RuleCall cTranslationBTSTranslationsParserRuleCall_20_1_0 = (RuleCall)cTranslationAssignment_20_1.eContents().get(0);
		private final Group cGroup_21 = (Group)cGroup.eContents().get(21);
		private final Keyword cGraphicsKeyword_21_0 = (Keyword)cGroup_21.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_21_1 = (Keyword)cGroup_21.eContents().get(1);
		private final Assignment cGraphicsAssignment_21_2 = (Assignment)cGroup_21.eContents().get(2);
		private final RuleCall cGraphicsBTSGraphicParserRuleCall_21_2_0 = (RuleCall)cGraphicsAssignment_21_2.eContents().get(0);
		private final Group cGroup_21_3 = (Group)cGroup_21.eContents().get(3);
		private final Keyword cCommaKeyword_21_3_0 = (Keyword)cGroup_21_3.eContents().get(0);
		private final Assignment cGraphicsAssignment_21_3_1 = (Assignment)cGroup_21_3.eContents().get(1);
		private final RuleCall cGraphicsBTSGraphicParserRuleCall_21_3_1_0 = (RuleCall)cGraphicsAssignment_21_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_21_4 = (Keyword)cGroup_21.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_22 = (Keyword)cGroup.eContents().get(22);
		
		//BTSWord:
		//	{BTSWord} "BTSWord" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)? ("visibility"
		//	visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)? ("code"
		//	code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("wType"
		//	wType=EString)? ("lType" lType=EString)? ("lKey" lKey=EString)? ("flexCode" flexCode=EString)? ("wChar"
		//	wChar=EString)? ("value" value=EString)? ("translation" translation=BTSTranslations)? ("graphics" "{"
		//	graphics+=BTSGraphic ("," graphics+=BTSGraphic)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{BTSWord} "BTSWord" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)? ("visibility"
		//visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)? ("code"
		//code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("wType"
		//wType=EString)? ("lType" lType=EString)? ("lKey" lKey=EString)? ("flexCode" flexCode=EString)? ("wChar"
		//wChar=EString)? ("value" value=EString)? ("translation" translation=BTSTranslations)? ("graphics" "{"
		//graphics+=BTSGraphic ("," graphics+=BTSGraphic)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{BTSWord}
		public Action getBTSWordAction_0() { return cBTSWordAction_0; }

		//"BTSWord"
		public Keyword getBTSWordKeyword_1() { return cBTSWordKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("state" state=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"state"
		public Keyword getStateKeyword_4_0() { return cStateKeyword_4_0; }

		//state=EString
		public Assignment getStateAssignment_4_1() { return cStateAssignment_4_1; }

		//EString
		public RuleCall getStateEStringParserRuleCall_4_1_0() { return cStateEStringParserRuleCall_4_1_0; }

		//("revisionState" revisionState=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"revisionState"
		public Keyword getRevisionStateKeyword_5_0() { return cRevisionStateKeyword_5_0; }

		//revisionState=EString
		public Assignment getRevisionStateAssignment_5_1() { return cRevisionStateAssignment_5_1; }

		//EString
		public RuleCall getRevisionStateEStringParserRuleCall_5_1_0() { return cRevisionStateEStringParserRuleCall_5_1_0; }

		//("visibility" visibility=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"visibility"
		public Keyword getVisibilityKeyword_6_0() { return cVisibilityKeyword_6_0; }

		//visibility=EString
		public Assignment getVisibilityAssignment_6_1() { return cVisibilityAssignment_6_1; }

		//EString
		public RuleCall getVisibilityEStringParserRuleCall_6_1_0() { return cVisibilityEStringParserRuleCall_6_1_0; }

		//("sortKey" sortKey=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"sortKey"
		public Keyword getSortKeyKeyword_7_0() { return cSortKeyKeyword_7_0; }

		//sortKey=EInt
		public Assignment getSortKeyAssignment_7_1() { return cSortKeyAssignment_7_1; }

		//EInt
		public RuleCall getSortKeyEIntParserRuleCall_7_1_0() { return cSortKeyEIntParserRuleCall_7_1_0; }

		//("type" type=EString)?
		public Group getGroup_8() { return cGroup_8; }

		//"type"
		public Keyword getTypeKeyword_8_0() { return cTypeKeyword_8_0; }

		//type=EString
		public Assignment getTypeAssignment_8_1() { return cTypeAssignment_8_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_8_1_0() { return cTypeEStringParserRuleCall_8_1_0; }

		//("subtype" subtype=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"subtype"
		public Keyword getSubtypeKeyword_9_0() { return cSubtypeKeyword_9_0; }

		//subtype=EString
		public Assignment getSubtypeAssignment_9_1() { return cSubtypeAssignment_9_1; }

		//EString
		public RuleCall getSubtypeEStringParserRuleCall_9_1_0() { return cSubtypeEStringParserRuleCall_9_1_0; }

		//("code" code=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"code"
		public Keyword getCodeKeyword_10_0() { return cCodeKeyword_10_0; }

		//code=EString
		public Assignment getCodeAssignment_10_1() { return cCodeAssignment_10_1; }

		//EString
		public RuleCall getCodeEStringParserRuleCall_10_1_0() { return cCodeEStringParserRuleCall_10_1_0; }

		//("_id" _id=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"_id"
		public Keyword get_idKeyword_11_0() { return c_idKeyword_11_0; }

		//_id=EString
		public Assignment get_idAssignment_11_1() { return c_idAssignment_11_1; }

		//EString
		public RuleCall get_idEStringParserRuleCall_11_1_0() { return c_idEStringParserRuleCall_11_1_0; }

		//("comment" comment=EString)?
		public Group getGroup_12() { return cGroup_12; }

		//"comment"
		public Keyword getCommentKeyword_12_0() { return cCommentKeyword_12_0; }

		//comment=EString
		public Assignment getCommentAssignment_12_1() { return cCommentAssignment_12_1; }

		//EString
		public RuleCall getCommentEStringParserRuleCall_12_1_0() { return cCommentEStringParserRuleCall_12_1_0; }

		//("parentId" parentId=EString)?
		public Group getGroup_13() { return cGroup_13; }

		//"parentId"
		public Keyword getParentIdKeyword_13_0() { return cParentIdKeyword_13_0; }

		//parentId=EString
		public Assignment getParentIdAssignment_13_1() { return cParentIdAssignment_13_1; }

		//EString
		public RuleCall getParentIdEStringParserRuleCall_13_1_0() { return cParentIdEStringParserRuleCall_13_1_0; }

		//("wType" wType=EString)?
		public Group getGroup_14() { return cGroup_14; }

		//"wType"
		public Keyword getWTypeKeyword_14_0() { return cWTypeKeyword_14_0; }

		//wType=EString
		public Assignment getWTypeAssignment_14_1() { return cWTypeAssignment_14_1; }

		//EString
		public RuleCall getWTypeEStringParserRuleCall_14_1_0() { return cWTypeEStringParserRuleCall_14_1_0; }

		//("lType" lType=EString)?
		public Group getGroup_15() { return cGroup_15; }

		//"lType"
		public Keyword getLTypeKeyword_15_0() { return cLTypeKeyword_15_0; }

		//lType=EString
		public Assignment getLTypeAssignment_15_1() { return cLTypeAssignment_15_1; }

		//EString
		public RuleCall getLTypeEStringParserRuleCall_15_1_0() { return cLTypeEStringParserRuleCall_15_1_0; }

		//("lKey" lKey=EString)?
		public Group getGroup_16() { return cGroup_16; }

		//"lKey"
		public Keyword getLKeyKeyword_16_0() { return cLKeyKeyword_16_0; }

		//lKey=EString
		public Assignment getLKeyAssignment_16_1() { return cLKeyAssignment_16_1; }

		//EString
		public RuleCall getLKeyEStringParserRuleCall_16_1_0() { return cLKeyEStringParserRuleCall_16_1_0; }

		//("flexCode" flexCode=EString)?
		public Group getGroup_17() { return cGroup_17; }

		//"flexCode"
		public Keyword getFlexCodeKeyword_17_0() { return cFlexCodeKeyword_17_0; }

		//flexCode=EString
		public Assignment getFlexCodeAssignment_17_1() { return cFlexCodeAssignment_17_1; }

		//EString
		public RuleCall getFlexCodeEStringParserRuleCall_17_1_0() { return cFlexCodeEStringParserRuleCall_17_1_0; }

		//("wChar" wChar=EString)?
		public Group getGroup_18() { return cGroup_18; }

		//"wChar"
		public Keyword getWCharKeyword_18_0() { return cWCharKeyword_18_0; }

		//wChar=EString
		public Assignment getWCharAssignment_18_1() { return cWCharAssignment_18_1; }

		//EString
		public RuleCall getWCharEStringParserRuleCall_18_1_0() { return cWCharEStringParserRuleCall_18_1_0; }

		//("value" value=EString)?
		public Group getGroup_19() { return cGroup_19; }

		//"value"
		public Keyword getValueKeyword_19_0() { return cValueKeyword_19_0; }

		//value=EString
		public Assignment getValueAssignment_19_1() { return cValueAssignment_19_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_19_1_0() { return cValueEStringParserRuleCall_19_1_0; }

		//("translation" translation=BTSTranslations)?
		public Group getGroup_20() { return cGroup_20; }

		//"translation"
		public Keyword getTranslationKeyword_20_0() { return cTranslationKeyword_20_0; }

		//translation=BTSTranslations
		public Assignment getTranslationAssignment_20_1() { return cTranslationAssignment_20_1; }

		//BTSTranslations
		public RuleCall getTranslationBTSTranslationsParserRuleCall_20_1_0() { return cTranslationBTSTranslationsParserRuleCall_20_1_0; }

		//("graphics" "{" graphics+=BTSGraphic ("," graphics+=BTSGraphic)* "}")?
		public Group getGroup_21() { return cGroup_21; }

		//"graphics"
		public Keyword getGraphicsKeyword_21_0() { return cGraphicsKeyword_21_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_21_1() { return cLeftCurlyBracketKeyword_21_1; }

		//graphics+=BTSGraphic
		public Assignment getGraphicsAssignment_21_2() { return cGraphicsAssignment_21_2; }

		//BTSGraphic
		public RuleCall getGraphicsBTSGraphicParserRuleCall_21_2_0() { return cGraphicsBTSGraphicParserRuleCall_21_2_0; }

		//("," graphics+=BTSGraphic)*
		public Group getGroup_21_3() { return cGroup_21_3; }

		//","
		public Keyword getCommaKeyword_21_3_0() { return cCommaKeyword_21_3_0; }

		//graphics+=BTSGraphic
		public Assignment getGraphicsAssignment_21_3_1() { return cGraphicsAssignment_21_3_1; }

		//BTSGraphic
		public RuleCall getGraphicsBTSGraphicParserRuleCall_21_3_1_0() { return cGraphicsBTSGraphicParserRuleCall_21_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_21_4() { return cRightCurlyBracketKeyword_21_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_22() { return cRightCurlyBracketKeyword_22; }
	}

	public class BTSMarkerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSMarker");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSMarkerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSMarkerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStateEStringParserRuleCall_4_1_0 = (RuleCall)cStateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRevisionStateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRevisionStateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRevisionStateEStringParserRuleCall_5_1_0 = (RuleCall)cRevisionStateAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cVisibilityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cVisibilityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cVisibilityEStringParserRuleCall_6_1_0 = (RuleCall)cVisibilityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSortKeyKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSortKeyAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSortKeyEIntParserRuleCall_7_1_0 = (RuleCall)cSortKeyAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cTypeKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cTypeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_8_1_0 = (RuleCall)cTypeAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSubtypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cSubtypeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cSubtypeEStringParserRuleCall_9_1_0 = (RuleCall)cSubtypeAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCodeKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCodeAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_10_1_0 = (RuleCall)cCodeAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword c_idKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment c_idAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall c_idEStringParserRuleCall_11_1_0 = (RuleCall)c_idAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommentKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cCommentAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cCommentEStringParserRuleCall_12_1_0 = (RuleCall)cCommentAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cParentIdKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cParentIdAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cParentIdEStringParserRuleCall_13_1_0 = (RuleCall)cParentIdAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cValueKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cValueAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_14_1_0 = (RuleCall)cValueAssignment_14_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//BTSMarker:
		//	{BTSMarker} "BTSMarker" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
		//	("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
		//	("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("value"
		//	value=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{BTSMarker} "BTSMarker" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)? ("visibility"
		//visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)? ("code"
		//code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("value"
		//value=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{BTSMarker}
		public Action getBTSMarkerAction_0() { return cBTSMarkerAction_0; }

		//"BTSMarker"
		public Keyword getBTSMarkerKeyword_1() { return cBTSMarkerKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("state" state=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"state"
		public Keyword getStateKeyword_4_0() { return cStateKeyword_4_0; }

		//state=EString
		public Assignment getStateAssignment_4_1() { return cStateAssignment_4_1; }

		//EString
		public RuleCall getStateEStringParserRuleCall_4_1_0() { return cStateEStringParserRuleCall_4_1_0; }

		//("revisionState" revisionState=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"revisionState"
		public Keyword getRevisionStateKeyword_5_0() { return cRevisionStateKeyword_5_0; }

		//revisionState=EString
		public Assignment getRevisionStateAssignment_5_1() { return cRevisionStateAssignment_5_1; }

		//EString
		public RuleCall getRevisionStateEStringParserRuleCall_5_1_0() { return cRevisionStateEStringParserRuleCall_5_1_0; }

		//("visibility" visibility=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"visibility"
		public Keyword getVisibilityKeyword_6_0() { return cVisibilityKeyword_6_0; }

		//visibility=EString
		public Assignment getVisibilityAssignment_6_1() { return cVisibilityAssignment_6_1; }

		//EString
		public RuleCall getVisibilityEStringParserRuleCall_6_1_0() { return cVisibilityEStringParserRuleCall_6_1_0; }

		//("sortKey" sortKey=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"sortKey"
		public Keyword getSortKeyKeyword_7_0() { return cSortKeyKeyword_7_0; }

		//sortKey=EInt
		public Assignment getSortKeyAssignment_7_1() { return cSortKeyAssignment_7_1; }

		//EInt
		public RuleCall getSortKeyEIntParserRuleCall_7_1_0() { return cSortKeyEIntParserRuleCall_7_1_0; }

		//("type" type=EString)?
		public Group getGroup_8() { return cGroup_8; }

		//"type"
		public Keyword getTypeKeyword_8_0() { return cTypeKeyword_8_0; }

		//type=EString
		public Assignment getTypeAssignment_8_1() { return cTypeAssignment_8_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_8_1_0() { return cTypeEStringParserRuleCall_8_1_0; }

		//("subtype" subtype=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"subtype"
		public Keyword getSubtypeKeyword_9_0() { return cSubtypeKeyword_9_0; }

		//subtype=EString
		public Assignment getSubtypeAssignment_9_1() { return cSubtypeAssignment_9_1; }

		//EString
		public RuleCall getSubtypeEStringParserRuleCall_9_1_0() { return cSubtypeEStringParserRuleCall_9_1_0; }

		//("code" code=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"code"
		public Keyword getCodeKeyword_10_0() { return cCodeKeyword_10_0; }

		//code=EString
		public Assignment getCodeAssignment_10_1() { return cCodeAssignment_10_1; }

		//EString
		public RuleCall getCodeEStringParserRuleCall_10_1_0() { return cCodeEStringParserRuleCall_10_1_0; }

		//("_id" _id=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"_id"
		public Keyword get_idKeyword_11_0() { return c_idKeyword_11_0; }

		//_id=EString
		public Assignment get_idAssignment_11_1() { return c_idAssignment_11_1; }

		//EString
		public RuleCall get_idEStringParserRuleCall_11_1_0() { return c_idEStringParserRuleCall_11_1_0; }

		//("comment" comment=EString)?
		public Group getGroup_12() { return cGroup_12; }

		//"comment"
		public Keyword getCommentKeyword_12_0() { return cCommentKeyword_12_0; }

		//comment=EString
		public Assignment getCommentAssignment_12_1() { return cCommentAssignment_12_1; }

		//EString
		public RuleCall getCommentEStringParserRuleCall_12_1_0() { return cCommentEStringParserRuleCall_12_1_0; }

		//("parentId" parentId=EString)?
		public Group getGroup_13() { return cGroup_13; }

		//"parentId"
		public Keyword getParentIdKeyword_13_0() { return cParentIdKeyword_13_0; }

		//parentId=EString
		public Assignment getParentIdAssignment_13_1() { return cParentIdAssignment_13_1; }

		//EString
		public RuleCall getParentIdEStringParserRuleCall_13_1_0() { return cParentIdEStringParserRuleCall_13_1_0; }

		//("value" value=EString)?
		public Group getGroup_14() { return cGroup_14; }

		//"value"
		public Keyword getValueKeyword_14_0() { return cValueKeyword_14_0; }

		//value=EString
		public Assignment getValueAssignment_14_1() { return cValueAssignment_14_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_14_1_0() { return cValueEStringParserRuleCall_14_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}

	public class BTSAmbivalenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSAmbivalence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSAmbivalenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSAmbivalenceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStateEStringParserRuleCall_4_1_0 = (RuleCall)cStateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRevisionStateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRevisionStateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRevisionStateEStringParserRuleCall_5_1_0 = (RuleCall)cRevisionStateAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cVisibilityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cVisibilityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cVisibilityEStringParserRuleCall_6_1_0 = (RuleCall)cVisibilityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSortKeyKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSortKeyAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSortKeyEIntParserRuleCall_7_1_0 = (RuleCall)cSortKeyAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cTypeKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cTypeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_8_1_0 = (RuleCall)cTypeAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSubtypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cSubtypeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cSubtypeEStringParserRuleCall_9_1_0 = (RuleCall)cSubtypeAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCodeKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCodeAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_10_1_0 = (RuleCall)cCodeAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword c_idKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment c_idAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall c_idEStringParserRuleCall_11_1_0 = (RuleCall)c_idAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommentKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cCommentAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cCommentEStringParserRuleCall_12_1_0 = (RuleCall)cCommentAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cParentIdKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cParentIdAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cParentIdEStringParserRuleCall_13_1_0 = (RuleCall)cParentIdAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cCasesKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cCasesAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final RuleCall cCasesBTSLemmaCaseParserRuleCall_14_2_0 = (RuleCall)cCasesAssignment_14_2.eContents().get(0);
		private final Group cGroup_14_3 = (Group)cGroup_14.eContents().get(3);
		private final Keyword cCommaKeyword_14_3_0 = (Keyword)cGroup_14_3.eContents().get(0);
		private final Assignment cCasesAssignment_14_3_1 = (Assignment)cGroup_14_3.eContents().get(1);
		private final RuleCall cCasesBTSLemmaCaseParserRuleCall_14_3_1_0 = (RuleCall)cCasesAssignment_14_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14_4 = (Keyword)cGroup_14.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//BTSAmbivalence:
		//	{BTSAmbivalence} "BTSAmbivalence" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
		//	("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
		//	("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("cases" "{"
		//	cases+=BTSLemmaCase ("," cases+=BTSLemmaCase)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{BTSAmbivalence} "BTSAmbivalence" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
		//("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
		//("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("cases" "{"
		//cases+=BTSLemmaCase ("," cases+=BTSLemmaCase)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{BTSAmbivalence}
		public Action getBTSAmbivalenceAction_0() { return cBTSAmbivalenceAction_0; }

		//"BTSAmbivalence"
		public Keyword getBTSAmbivalenceKeyword_1() { return cBTSAmbivalenceKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("state" state=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"state"
		public Keyword getStateKeyword_4_0() { return cStateKeyword_4_0; }

		//state=EString
		public Assignment getStateAssignment_4_1() { return cStateAssignment_4_1; }

		//EString
		public RuleCall getStateEStringParserRuleCall_4_1_0() { return cStateEStringParserRuleCall_4_1_0; }

		//("revisionState" revisionState=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"revisionState"
		public Keyword getRevisionStateKeyword_5_0() { return cRevisionStateKeyword_5_0; }

		//revisionState=EString
		public Assignment getRevisionStateAssignment_5_1() { return cRevisionStateAssignment_5_1; }

		//EString
		public RuleCall getRevisionStateEStringParserRuleCall_5_1_0() { return cRevisionStateEStringParserRuleCall_5_1_0; }

		//("visibility" visibility=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"visibility"
		public Keyword getVisibilityKeyword_6_0() { return cVisibilityKeyword_6_0; }

		//visibility=EString
		public Assignment getVisibilityAssignment_6_1() { return cVisibilityAssignment_6_1; }

		//EString
		public RuleCall getVisibilityEStringParserRuleCall_6_1_0() { return cVisibilityEStringParserRuleCall_6_1_0; }

		//("sortKey" sortKey=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"sortKey"
		public Keyword getSortKeyKeyword_7_0() { return cSortKeyKeyword_7_0; }

		//sortKey=EInt
		public Assignment getSortKeyAssignment_7_1() { return cSortKeyAssignment_7_1; }

		//EInt
		public RuleCall getSortKeyEIntParserRuleCall_7_1_0() { return cSortKeyEIntParserRuleCall_7_1_0; }

		//("type" type=EString)?
		public Group getGroup_8() { return cGroup_8; }

		//"type"
		public Keyword getTypeKeyword_8_0() { return cTypeKeyword_8_0; }

		//type=EString
		public Assignment getTypeAssignment_8_1() { return cTypeAssignment_8_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_8_1_0() { return cTypeEStringParserRuleCall_8_1_0; }

		//("subtype" subtype=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"subtype"
		public Keyword getSubtypeKeyword_9_0() { return cSubtypeKeyword_9_0; }

		//subtype=EString
		public Assignment getSubtypeAssignment_9_1() { return cSubtypeAssignment_9_1; }

		//EString
		public RuleCall getSubtypeEStringParserRuleCall_9_1_0() { return cSubtypeEStringParserRuleCall_9_1_0; }

		//("code" code=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"code"
		public Keyword getCodeKeyword_10_0() { return cCodeKeyword_10_0; }

		//code=EString
		public Assignment getCodeAssignment_10_1() { return cCodeAssignment_10_1; }

		//EString
		public RuleCall getCodeEStringParserRuleCall_10_1_0() { return cCodeEStringParserRuleCall_10_1_0; }

		//("_id" _id=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"_id"
		public Keyword get_idKeyword_11_0() { return c_idKeyword_11_0; }

		//_id=EString
		public Assignment get_idAssignment_11_1() { return c_idAssignment_11_1; }

		//EString
		public RuleCall get_idEStringParserRuleCall_11_1_0() { return c_idEStringParserRuleCall_11_1_0; }

		//("comment" comment=EString)?
		public Group getGroup_12() { return cGroup_12; }

		//"comment"
		public Keyword getCommentKeyword_12_0() { return cCommentKeyword_12_0; }

		//comment=EString
		public Assignment getCommentAssignment_12_1() { return cCommentAssignment_12_1; }

		//EString
		public RuleCall getCommentEStringParserRuleCall_12_1_0() { return cCommentEStringParserRuleCall_12_1_0; }

		//("parentId" parentId=EString)?
		public Group getGroup_13() { return cGroup_13; }

		//"parentId"
		public Keyword getParentIdKeyword_13_0() { return cParentIdKeyword_13_0; }

		//parentId=EString
		public Assignment getParentIdAssignment_13_1() { return cParentIdAssignment_13_1; }

		//EString
		public RuleCall getParentIdEStringParserRuleCall_13_1_0() { return cParentIdEStringParserRuleCall_13_1_0; }

		//("cases" "{" cases+=BTSLemmaCase ("," cases+=BTSLemmaCase)* "}")?
		public Group getGroup_14() { return cGroup_14; }

		//"cases"
		public Keyword getCasesKeyword_14_0() { return cCasesKeyword_14_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_14_1() { return cLeftCurlyBracketKeyword_14_1; }

		//cases+=BTSLemmaCase
		public Assignment getCasesAssignment_14_2() { return cCasesAssignment_14_2; }

		//BTSLemmaCase
		public RuleCall getCasesBTSLemmaCaseParserRuleCall_14_2_0() { return cCasesBTSLemmaCaseParserRuleCall_14_2_0; }

		//("," cases+=BTSLemmaCase)*
		public Group getGroup_14_3() { return cGroup_14_3; }

		//","
		public Keyword getCommaKeyword_14_3_0() { return cCommaKeyword_14_3_0; }

		//cases+=BTSLemmaCase
		public Assignment getCasesAssignment_14_3_1() { return cCasesAssignment_14_3_1; }

		//BTSLemmaCase
		public RuleCall getCasesBTSLemmaCaseParserRuleCall_14_3_1_0() { return cCasesBTSLemmaCaseParserRuleCall_14_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14_4() { return cRightCurlyBracketKeyword_14_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}

	public class BTSLemmaCaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSLemmaCase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSLemmaCaseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSLemmaCaseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStateEStringParserRuleCall_4_1_0 = (RuleCall)cStateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRevisionStateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRevisionStateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRevisionStateEStringParserRuleCall_5_1_0 = (RuleCall)cRevisionStateAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cVisibilityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cVisibilityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cVisibilityEStringParserRuleCall_6_1_0 = (RuleCall)cVisibilityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSortKeyKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSortKeyAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSortKeyEIntParserRuleCall_7_1_0 = (RuleCall)cSortKeyAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cTypeKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cTypeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_8_1_0 = (RuleCall)cTypeAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSubtypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cSubtypeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cSubtypeEStringParserRuleCall_9_1_0 = (RuleCall)cSubtypeAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCodeKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCodeAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_10_1_0 = (RuleCall)cCodeAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword c_idKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment c_idAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall c_idEStringParserRuleCall_11_1_0 = (RuleCall)c_idAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommentKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cCommentAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cCommentEStringParserRuleCall_12_1_0 = (RuleCall)cCommentAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cParentIdKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cParentIdAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cParentIdEStringParserRuleCall_13_1_0 = (RuleCall)cParentIdAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cScenarioKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cScenarioAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final RuleCall cScenarioBTSAmbivalenceItemParserRuleCall_14_2_0 = (RuleCall)cScenarioAssignment_14_2.eContents().get(0);
		private final Group cGroup_14_3 = (Group)cGroup_14.eContents().get(3);
		private final Keyword cCommaKeyword_14_3_0 = (Keyword)cGroup_14_3.eContents().get(0);
		private final Assignment cScenarioAssignment_14_3_1 = (Assignment)cGroup_14_3.eContents().get(1);
		private final RuleCall cScenarioBTSAmbivalenceItemParserRuleCall_14_3_1_0 = (RuleCall)cScenarioAssignment_14_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14_4 = (Keyword)cGroup_14.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//BTSLemmaCase:
		//	{BTSLemmaCase} "BTSLemmaCase" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
		//	("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
		//	("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("scenario"
		//	"{" scenario+=BTSAmbivalenceItem ("," scenario+=BTSAmbivalenceItem)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{BTSLemmaCase} "BTSLemmaCase" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
		//("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
		//("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("scenario"
		//"{" scenario+=BTSAmbivalenceItem ("," scenario+=BTSAmbivalenceItem)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{BTSLemmaCase}
		public Action getBTSLemmaCaseAction_0() { return cBTSLemmaCaseAction_0; }

		//"BTSLemmaCase"
		public Keyword getBTSLemmaCaseKeyword_1() { return cBTSLemmaCaseKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("state" state=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"state"
		public Keyword getStateKeyword_4_0() { return cStateKeyword_4_0; }

		//state=EString
		public Assignment getStateAssignment_4_1() { return cStateAssignment_4_1; }

		//EString
		public RuleCall getStateEStringParserRuleCall_4_1_0() { return cStateEStringParserRuleCall_4_1_0; }

		//("revisionState" revisionState=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"revisionState"
		public Keyword getRevisionStateKeyword_5_0() { return cRevisionStateKeyword_5_0; }

		//revisionState=EString
		public Assignment getRevisionStateAssignment_5_1() { return cRevisionStateAssignment_5_1; }

		//EString
		public RuleCall getRevisionStateEStringParserRuleCall_5_1_0() { return cRevisionStateEStringParserRuleCall_5_1_0; }

		//("visibility" visibility=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"visibility"
		public Keyword getVisibilityKeyword_6_0() { return cVisibilityKeyword_6_0; }

		//visibility=EString
		public Assignment getVisibilityAssignment_6_1() { return cVisibilityAssignment_6_1; }

		//EString
		public RuleCall getVisibilityEStringParserRuleCall_6_1_0() { return cVisibilityEStringParserRuleCall_6_1_0; }

		//("sortKey" sortKey=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"sortKey"
		public Keyword getSortKeyKeyword_7_0() { return cSortKeyKeyword_7_0; }

		//sortKey=EInt
		public Assignment getSortKeyAssignment_7_1() { return cSortKeyAssignment_7_1; }

		//EInt
		public RuleCall getSortKeyEIntParserRuleCall_7_1_0() { return cSortKeyEIntParserRuleCall_7_1_0; }

		//("type" type=EString)?
		public Group getGroup_8() { return cGroup_8; }

		//"type"
		public Keyword getTypeKeyword_8_0() { return cTypeKeyword_8_0; }

		//type=EString
		public Assignment getTypeAssignment_8_1() { return cTypeAssignment_8_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_8_1_0() { return cTypeEStringParserRuleCall_8_1_0; }

		//("subtype" subtype=EString)?
		public Group getGroup_9() { return cGroup_9; }

		//"subtype"
		public Keyword getSubtypeKeyword_9_0() { return cSubtypeKeyword_9_0; }

		//subtype=EString
		public Assignment getSubtypeAssignment_9_1() { return cSubtypeAssignment_9_1; }

		//EString
		public RuleCall getSubtypeEStringParserRuleCall_9_1_0() { return cSubtypeEStringParserRuleCall_9_1_0; }

		//("code" code=EString)?
		public Group getGroup_10() { return cGroup_10; }

		//"code"
		public Keyword getCodeKeyword_10_0() { return cCodeKeyword_10_0; }

		//code=EString
		public Assignment getCodeAssignment_10_1() { return cCodeAssignment_10_1; }

		//EString
		public RuleCall getCodeEStringParserRuleCall_10_1_0() { return cCodeEStringParserRuleCall_10_1_0; }

		//("_id" _id=EString)?
		public Group getGroup_11() { return cGroup_11; }

		//"_id"
		public Keyword get_idKeyword_11_0() { return c_idKeyword_11_0; }

		//_id=EString
		public Assignment get_idAssignment_11_1() { return c_idAssignment_11_1; }

		//EString
		public RuleCall get_idEStringParserRuleCall_11_1_0() { return c_idEStringParserRuleCall_11_1_0; }

		//("comment" comment=EString)?
		public Group getGroup_12() { return cGroup_12; }

		//"comment"
		public Keyword getCommentKeyword_12_0() { return cCommentKeyword_12_0; }

		//comment=EString
		public Assignment getCommentAssignment_12_1() { return cCommentAssignment_12_1; }

		//EString
		public RuleCall getCommentEStringParserRuleCall_12_1_0() { return cCommentEStringParserRuleCall_12_1_0; }

		//("parentId" parentId=EString)?
		public Group getGroup_13() { return cGroup_13; }

		//"parentId"
		public Keyword getParentIdKeyword_13_0() { return cParentIdKeyword_13_0; }

		//parentId=EString
		public Assignment getParentIdAssignment_13_1() { return cParentIdAssignment_13_1; }

		//EString
		public RuleCall getParentIdEStringParserRuleCall_13_1_0() { return cParentIdEStringParserRuleCall_13_1_0; }

		//("scenario" "{" scenario+=BTSAmbivalenceItem ("," scenario+=BTSAmbivalenceItem)* "}")?
		public Group getGroup_14() { return cGroup_14; }

		//"scenario"
		public Keyword getScenarioKeyword_14_0() { return cScenarioKeyword_14_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_14_1() { return cLeftCurlyBracketKeyword_14_1; }

		//scenario+=BTSAmbivalenceItem
		public Assignment getScenarioAssignment_14_2() { return cScenarioAssignment_14_2; }

		//BTSAmbivalenceItem
		public RuleCall getScenarioBTSAmbivalenceItemParserRuleCall_14_2_0() { return cScenarioBTSAmbivalenceItemParserRuleCall_14_2_0; }

		//("," scenario+=BTSAmbivalenceItem)*
		public Group getGroup_14_3() { return cGroup_14_3; }

		//","
		public Keyword getCommaKeyword_14_3_0() { return cCommaKeyword_14_3_0; }

		//scenario+=BTSAmbivalenceItem
		public Assignment getScenarioAssignment_14_3_1() { return cScenarioAssignment_14_3_1; }

		//BTSAmbivalenceItem
		public RuleCall getScenarioBTSAmbivalenceItemParserRuleCall_14_3_1_0() { return cScenarioBTSAmbivalenceItemParserRuleCall_14_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14_4() { return cRightCurlyBracketKeyword_14_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class BTSTranslationsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSTranslations");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSTranslationsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSTranslationsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTranslationsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cTranslationsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cTranslationsBTSTranslationParserRuleCall_3_2_0 = (RuleCall)cTranslationsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cTranslationsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cTranslationsBTSTranslationParserRuleCall_3_3_1_0 = (RuleCall)cTranslationsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//BTSTranslations:
		//	{BTSTranslations} "BTSTranslations" "{" ("translations" "{" translations+=BTSTranslation (","
		//	translations+=BTSTranslation)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{BTSTranslations} "BTSTranslations" "{" ("translations" "{" translations+=BTSTranslation (","
		//translations+=BTSTranslation)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{BTSTranslations}
		public Action getBTSTranslationsAction_0() { return cBTSTranslationsAction_0; }

		//"BTSTranslations"
		public Keyword getBTSTranslationsKeyword_1() { return cBTSTranslationsKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("translations" "{" translations+=BTSTranslation ("," translations+=BTSTranslation)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"translations"
		public Keyword getTranslationsKeyword_3_0() { return cTranslationsKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//translations+=BTSTranslation
		public Assignment getTranslationsAssignment_3_2() { return cTranslationsAssignment_3_2; }

		//BTSTranslation
		public RuleCall getTranslationsBTSTranslationParserRuleCall_3_2_0() { return cTranslationsBTSTranslationParserRuleCall_3_2_0; }

		//("," translations+=BTSTranslation)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//translations+=BTSTranslation
		public Assignment getTranslationsAssignment_3_3_1() { return cTranslationsAssignment_3_3_1; }

		//BTSTranslation
		public RuleCall getTranslationsBTSTranslationParserRuleCall_3_3_1_0() { return cTranslationsBTSTranslationParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class BTSTranslationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSTranslation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSTranslationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSTranslationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLangKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLangAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLangEStringParserRuleCall_5_1_0 = (RuleCall)cLangAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//BTSTranslation:
		//	{BTSTranslation} "BTSTranslation" "{" ("value" value=EString)? ("type" type=EString)? ("lang" lang=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{BTSTranslation} "BTSTranslation" "{" ("value" value=EString)? ("type" type=EString)? ("lang" lang=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{BTSTranslation}
		public Action getBTSTranslationAction_0() { return cBTSTranslationAction_0; }

		//"BTSTranslation"
		public Keyword getBTSTranslationKeyword_1() { return cBTSTranslationKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("value" value=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"value"
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }

		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }

		//("type" type=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"type"
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }

		//type=EString
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_4_1_0() { return cTypeEStringParserRuleCall_4_1_0; }

		//("lang" lang=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"lang"
		public Keyword getLangKeyword_5_0() { return cLangKeyword_5_0; }

		//lang=EString
		public Assignment getLangAssignment_5_1() { return cLangAssignment_5_1; }

		//EString
		public RuleCall getLangEStringParserRuleCall_5_1_0() { return cLangEStringParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class BTSGraphicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BTSGraphic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBTSGraphicAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBTSGraphicKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword c_idKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment c_idAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall c_idEStringParserRuleCall_3_1_0 = (RuleCall)c_idAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cInnerSentenceOrderKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInnerSentenceOrderAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInnerSentenceOrderEIntParserRuleCall_4_1_0 = (RuleCall)cInnerSentenceOrderAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCodeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCodeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_5_1_0 = (RuleCall)cCodeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cReferenceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cReferenceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cReferenceEStringParserRuleCall_6_1_0 = (RuleCall)cReferenceAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//BTSGraphic:
		//	{BTSGraphic} "BTSGraphic" "{" ("_id" _id=EString)? ("innerSentenceOrder" innerSentenceOrder=EInt)? ("code"
		//	code=EString)? ("reference" reference=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{BTSGraphic} "BTSGraphic" "{" ("_id" _id=EString)? ("innerSentenceOrder" innerSentenceOrder=EInt)? ("code"
		//code=EString)? ("reference" reference=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{BTSGraphic}
		public Action getBTSGraphicAction_0() { return cBTSGraphicAction_0; }

		//"BTSGraphic"
		public Keyword getBTSGraphicKeyword_1() { return cBTSGraphicKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("_id" _id=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"_id"
		public Keyword get_idKeyword_3_0() { return c_idKeyword_3_0; }

		//_id=EString
		public Assignment get_idAssignment_3_1() { return c_idAssignment_3_1; }

		//EString
		public RuleCall get_idEStringParserRuleCall_3_1_0() { return c_idEStringParserRuleCall_3_1_0; }

		//("innerSentenceOrder" innerSentenceOrder=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"innerSentenceOrder"
		public Keyword getInnerSentenceOrderKeyword_4_0() { return cInnerSentenceOrderKeyword_4_0; }

		//innerSentenceOrder=EInt
		public Assignment getInnerSentenceOrderAssignment_4_1() { return cInnerSentenceOrderAssignment_4_1; }

		//EInt
		public RuleCall getInnerSentenceOrderEIntParserRuleCall_4_1_0() { return cInnerSentenceOrderEIntParserRuleCall_4_1_0; }

		//("code" code=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"code"
		public Keyword getCodeKeyword_5_0() { return cCodeKeyword_5_0; }

		//code=EString
		public Assignment getCodeAssignment_5_1() { return cCodeAssignment_5_1; }

		//EString
		public RuleCall getCodeEStringParserRuleCall_5_1_0() { return cCodeEStringParserRuleCall_5_1_0; }

		//("reference" reference=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"reference"
		public Keyword getReferenceKeyword_6_0() { return cReferenceKeyword_6_0; }

		//reference=EString
		public Assignment getReferenceAssignment_6_1() { return cReferenceAssignment_6_1; }

		//EString
		public RuleCall getReferenceEStringParserRuleCall_6_1_0() { return cReferenceEStringParserRuleCall_6_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private BTSTextContentElements pBTSTextContent;
	private BTSSentenceItemElements pBTSSentenceItem;
	private BTSAmbivalenceItemElements pBTSAmbivalenceItem;
	private BTSTextItemsElements pBTSTextItems;
	private EStringElements pEString;
	private BTSSenctenceElements pBTSSenctence;
	private BTSWordElements pBTSWord;
	private BTSMarkerElements pBTSMarker;
	private BTSAmbivalenceElements pBTSAmbivalence;
	private BTSLemmaCaseElements pBTSLemmaCase;
	private EIntElements pEInt;
	private BTSTranslationsElements pBTSTranslations;
	private BTSTranslationElements pBTSTranslation;
	private BTSGraphicElements pBTSGraphic;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public BTSGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.bbaw.bts.corpus.text.btsdsl.BTS".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//BTSTextContent:
	//	{BTSTextContent} "BTSTextContent" "{" ("textItems" "{" textItems+=BTSTextItems ("," textItems+=BTSTextItems)* "}")?
	//	"}";
	public BTSTextContentElements getBTSTextContentAccess() {
		return (pBTSTextContent != null) ? pBTSTextContent : (pBTSTextContent = new BTSTextContentElements());
	}
	
	public ParserRule getBTSTextContentRule() {
		return getBTSTextContentAccess().getRule();
	}

	//BTSSentenceItem:
	//	BTSWord | BTSMarker | BTSAmbivalence;
	public BTSSentenceItemElements getBTSSentenceItemAccess() {
		return (pBTSSentenceItem != null) ? pBTSSentenceItem : (pBTSSentenceItem = new BTSSentenceItemElements());
	}
	
	public ParserRule getBTSSentenceItemRule() {
		return getBTSSentenceItemAccess().getRule();
	}

	//BTSAmbivalenceItem:
	//	BTSWord | BTSMarker;
	public BTSAmbivalenceItemElements getBTSAmbivalenceItemAccess() {
		return (pBTSAmbivalenceItem != null) ? pBTSAmbivalenceItem : (pBTSAmbivalenceItem = new BTSAmbivalenceItemElements());
	}
	
	public ParserRule getBTSAmbivalenceItemRule() {
		return getBTSAmbivalenceItemAccess().getRule();
	}

	//BTSTextItems:
	//	BTSSenctence | BTSMarker | BTSAmbivalence;
	public BTSTextItemsElements getBTSTextItemsAccess() {
		return (pBTSTextItems != null) ? pBTSTextItems : (pBTSTextItems = new BTSTextItemsElements());
	}
	
	public ParserRule getBTSTextItemsRule() {
		return getBTSTextItemsAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//BTSSenctence:
	//	{BTSSenctence} "BTSSenctence" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
	//	("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
	//	("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)?
	//	("sentenceItems" "{" sentenceItems+=BTSSentenceItem ("," sentenceItems+=BTSSentenceItem)* "}")? ("translation"
	//	translation=BTSTranslations)? "}";
	public BTSSenctenceElements getBTSSenctenceAccess() {
		return (pBTSSenctence != null) ? pBTSSenctence : (pBTSSenctence = new BTSSenctenceElements());
	}
	
	public ParserRule getBTSSenctenceRule() {
		return getBTSSenctenceAccess().getRule();
	}

	//BTSWord:
	//	{BTSWord} "BTSWord" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)? ("visibility"
	//	visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)? ("code"
	//	code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("wType"
	//	wType=EString)? ("lType" lType=EString)? ("lKey" lKey=EString)? ("flexCode" flexCode=EString)? ("wChar"
	//	wChar=EString)? ("value" value=EString)? ("translation" translation=BTSTranslations)? ("graphics" "{"
	//	graphics+=BTSGraphic ("," graphics+=BTSGraphic)* "}")? "}";
	public BTSWordElements getBTSWordAccess() {
		return (pBTSWord != null) ? pBTSWord : (pBTSWord = new BTSWordElements());
	}
	
	public ParserRule getBTSWordRule() {
		return getBTSWordAccess().getRule();
	}

	//BTSMarker:
	//	{BTSMarker} "BTSMarker" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
	//	("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
	//	("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("value"
	//	value=EString)? "}";
	public BTSMarkerElements getBTSMarkerAccess() {
		return (pBTSMarker != null) ? pBTSMarker : (pBTSMarker = new BTSMarkerElements());
	}
	
	public ParserRule getBTSMarkerRule() {
		return getBTSMarkerAccess().getRule();
	}

	//BTSAmbivalence:
	//	{BTSAmbivalence} "BTSAmbivalence" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
	//	("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
	//	("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("cases" "{"
	//	cases+=BTSLemmaCase ("," cases+=BTSLemmaCase)* "}")? "}";
	public BTSAmbivalenceElements getBTSAmbivalenceAccess() {
		return (pBTSAmbivalence != null) ? pBTSAmbivalence : (pBTSAmbivalence = new BTSAmbivalenceElements());
	}
	
	public ParserRule getBTSAmbivalenceRule() {
		return getBTSAmbivalenceAccess().getRule();
	}

	//BTSLemmaCase:
	//	{BTSLemmaCase} "BTSLemmaCase" name=EString "{" ("state" state=EString)? ("revisionState" revisionState=EString)?
	//	("visibility" visibility=EString)? ("sortKey" sortKey=EInt)? ("type" type=EString)? ("subtype" subtype=EString)?
	//	("code" code=EString)? ("_id" _id=EString)? ("comment" comment=EString)? ("parentId" parentId=EString)? ("scenario"
	//	"{" scenario+=BTSAmbivalenceItem ("," scenario+=BTSAmbivalenceItem)* "}")? "}";
	public BTSLemmaCaseElements getBTSLemmaCaseAccess() {
		return (pBTSLemmaCase != null) ? pBTSLemmaCase : (pBTSLemmaCase = new BTSLemmaCaseElements());
	}
	
	public ParserRule getBTSLemmaCaseRule() {
		return getBTSLemmaCaseAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//BTSTranslations:
	//	{BTSTranslations} "BTSTranslations" "{" ("translations" "{" translations+=BTSTranslation (","
	//	translations+=BTSTranslation)* "}")? "}";
	public BTSTranslationsElements getBTSTranslationsAccess() {
		return (pBTSTranslations != null) ? pBTSTranslations : (pBTSTranslations = new BTSTranslationsElements());
	}
	
	public ParserRule getBTSTranslationsRule() {
		return getBTSTranslationsAccess().getRule();
	}

	//BTSTranslation:
	//	{BTSTranslation} "BTSTranslation" "{" ("value" value=EString)? ("type" type=EString)? ("lang" lang=EString)? "}";
	public BTSTranslationElements getBTSTranslationAccess() {
		return (pBTSTranslation != null) ? pBTSTranslation : (pBTSTranslation = new BTSTranslationElements());
	}
	
	public ParserRule getBTSTranslationRule() {
		return getBTSTranslationAccess().getRule();
	}

	//BTSGraphic:
	//	{BTSGraphic} "BTSGraphic" "{" ("_id" _id=EString)? ("innerSentenceOrder" innerSentenceOrder=EInt)? ("code"
	//	code=EString)? ("reference" reference=EString)? "}";
	public BTSGraphicElements getBTSGraphicAccess() {
		return (pBTSGraphic != null) ? pBTSGraphic : (pBTSGraphic = new BTSGraphicElements());
	}
	
	public ParserRule getBTSGraphicRule() {
		return getBTSGraphicAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
