/*
* generated by Xtext
*/
package org.bbaw.bts.corpus.text.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.bbaw.bts.corpus.text.dsl.services.BTSGrammarAccess;

public class BTSParser extends AbstractContentAssistParser {
	
	@Inject
	private BTSGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.bbaw.bts.corpus.text.dsl.ui.contentassist.antlr.internal.InternalBTSParser createParser() {
		org.bbaw.bts.corpus.text.dsl.ui.contentassist.antlr.internal.InternalBTSParser result = new org.bbaw.bts.corpus.text.dsl.ui.contentassist.antlr.internal.InternalBTSParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBTSTextContentAccess().getAlternatives_1_1(), "rule__BTSTextContent__Alternatives_1_1");
					put(grammarAccess.getBTSSentenceItemAccess().getAlternatives(), "rule__BTSSentenceItem__Alternatives");
					put(grammarAccess.getBTSAmbivalenceItemAccess().getAlternatives(), "rule__BTSAmbivalenceItem__Alternatives");
					put(grammarAccess.getBTSTextItemsAccess().getAlternatives(), "rule__BTSTextItems__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getBTSTextContentAccess().getGroup(), "rule__BTSTextContent__Group__0");
					put(grammarAccess.getBTSTextContentAccess().getGroup_1(), "rule__BTSTextContent__Group_1__0");
					put(grammarAccess.getBTSTextContentAccess().getGroup_1_1_1(), "rule__BTSTextContent__Group_1_1_1__0");
					put(grammarAccess.getBTSTextContentAccess().getGroup_1_2(), "rule__BTSTextContent__Group_1_2__0");
					put(grammarAccess.getBTSSenctenceAccess().getGroup(), "rule__BTSSenctence__Group__0");
					put(grammarAccess.getBTSSenctenceAccess().getGroup_2(), "rule__BTSSenctence__Group_2__0");
					put(grammarAccess.getBTSSenctenceAccess().getGroup_2_1(), "rule__BTSSenctence__Group_2_1__0");
					put(grammarAccess.getBTSWordAccess().getGroup(), "rule__BTSWord__Group__0");
					put(grammarAccess.getBTSMarkerAccess().getGroup(), "rule__BTSMarker__Group__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup(), "rule__BTSAmbivalence__Group__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_3(), "rule__BTSAmbivalence__Group_3__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_4(), "rule__BTSAmbivalence__Group_4__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_5(), "rule__BTSAmbivalence__Group_5__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_6(), "rule__BTSAmbivalence__Group_6__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_7(), "rule__BTSAmbivalence__Group_7__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_8(), "rule__BTSAmbivalence__Group_8__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_9(), "rule__BTSAmbivalence__Group_9__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_10(), "rule__BTSAmbivalence__Group_10__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_11(), "rule__BTSAmbivalence__Group_11__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_12(), "rule__BTSAmbivalence__Group_12__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_13(), "rule__BTSAmbivalence__Group_13__0");
					put(grammarAccess.getBTSAmbivalenceAccess().getGroup_13_3(), "rule__BTSAmbivalence__Group_13_3__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup(), "rule__BTSLemmaCase__Group__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_4(), "rule__BTSLemmaCase__Group_4__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_5(), "rule__BTSLemmaCase__Group_5__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_6(), "rule__BTSLemmaCase__Group_6__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_7(), "rule__BTSLemmaCase__Group_7__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_8(), "rule__BTSLemmaCase__Group_8__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_9(), "rule__BTSLemmaCase__Group_9__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_10(), "rule__BTSLemmaCase__Group_10__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_11(), "rule__BTSLemmaCase__Group_11__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_12(), "rule__BTSLemmaCase__Group_12__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_13(), "rule__BTSLemmaCase__Group_13__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_14(), "rule__BTSLemmaCase__Group_14__0");
					put(grammarAccess.getBTSLemmaCaseAccess().getGroup_14_3(), "rule__BTSLemmaCase__Group_14_3__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getBTSGraphicAccess().getGroup(), "rule__BTSGraphic__Group__0");
					put(grammarAccess.getBTSGraphicAccess().getGroup_3(), "rule__BTSGraphic__Group_3__0");
					put(grammarAccess.getBTSGraphicAccess().getGroup_4(), "rule__BTSGraphic__Group_4__0");
					put(grammarAccess.getBTSGraphicAccess().getGroup_5(), "rule__BTSGraphic__Group_5__0");
					put(grammarAccess.getBTSGraphicAccess().getGroup_6(), "rule__BTSGraphic__Group_6__0");
					put(grammarAccess.getBTSTextContentAccess().getTextItemsAssignment_1_0(), "rule__BTSTextContent__TextItemsAssignment_1_0");
					put(grammarAccess.getBTSTextContentAccess().getTextItemsAssignment_1_1_1_1(), "rule__BTSTextContent__TextItemsAssignment_1_1_1_1");
					put(grammarAccess.getBTSTextContentAccess().getTextItemsAssignment_1_2_1(), "rule__BTSTextContent__TextItemsAssignment_1_2_1");
					put(grammarAccess.getBTSSenctenceAccess().getSentenceItemsAssignment_2_0(), "rule__BTSSenctence__SentenceItemsAssignment_2_0");
					put(grammarAccess.getBTSSenctenceAccess().getSentenceItemsAssignment_2_1_1(), "rule__BTSSenctence__SentenceItemsAssignment_2_1_1");
					put(grammarAccess.getBTSWordAccess().getWCharAssignment_1(), "rule__BTSWord__WCharAssignment_1");
					put(grammarAccess.getBTSMarkerAccess().getValueAssignment_2(), "rule__BTSMarker__ValueAssignment_2");
					put(grammarAccess.getBTSAmbivalenceAccess().getStateAssignment_3_1(), "rule__BTSAmbivalence__StateAssignment_3_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getRevisionStateAssignment_4_1(), "rule__BTSAmbivalence__RevisionStateAssignment_4_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getVisibilityAssignment_5_1(), "rule__BTSAmbivalence__VisibilityAssignment_5_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getSortKeyAssignment_6_1(), "rule__BTSAmbivalence__SortKeyAssignment_6_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getTypeAssignment_7_1(), "rule__BTSAmbivalence__TypeAssignment_7_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getSubtypeAssignment_8_1(), "rule__BTSAmbivalence__SubtypeAssignment_8_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getCodeAssignment_9_1(), "rule__BTSAmbivalence__CodeAssignment_9_1");
					put(grammarAccess.getBTSAmbivalenceAccess().get_idAssignment_10_1(), "rule__BTSAmbivalence___idAssignment_10_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getCommentAssignment_11_1(), "rule__BTSAmbivalence__CommentAssignment_11_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getParentIdAssignment_12_1(), "rule__BTSAmbivalence__ParentIdAssignment_12_1");
					put(grammarAccess.getBTSAmbivalenceAccess().getCasesAssignment_13_2(), "rule__BTSAmbivalence__CasesAssignment_13_2");
					put(grammarAccess.getBTSAmbivalenceAccess().getCasesAssignment_13_3_1(), "rule__BTSAmbivalence__CasesAssignment_13_3_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getNameAssignment_2(), "rule__BTSLemmaCase__NameAssignment_2");
					put(grammarAccess.getBTSLemmaCaseAccess().getStateAssignment_4_1(), "rule__BTSLemmaCase__StateAssignment_4_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getRevisionStateAssignment_5_1(), "rule__BTSLemmaCase__RevisionStateAssignment_5_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getVisibilityAssignment_6_1(), "rule__BTSLemmaCase__VisibilityAssignment_6_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getSortKeyAssignment_7_1(), "rule__BTSLemmaCase__SortKeyAssignment_7_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getTypeAssignment_8_1(), "rule__BTSLemmaCase__TypeAssignment_8_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getSubtypeAssignment_9_1(), "rule__BTSLemmaCase__SubtypeAssignment_9_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getCodeAssignment_10_1(), "rule__BTSLemmaCase__CodeAssignment_10_1");
					put(grammarAccess.getBTSLemmaCaseAccess().get_idAssignment_11_1(), "rule__BTSLemmaCase___idAssignment_11_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getCommentAssignment_12_1(), "rule__BTSLemmaCase__CommentAssignment_12_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getParentIdAssignment_13_1(), "rule__BTSLemmaCase__ParentIdAssignment_13_1");
					put(grammarAccess.getBTSLemmaCaseAccess().getScenarioAssignment_14_2(), "rule__BTSLemmaCase__ScenarioAssignment_14_2");
					put(grammarAccess.getBTSLemmaCaseAccess().getScenarioAssignment_14_3_1(), "rule__BTSLemmaCase__ScenarioAssignment_14_3_1");
					put(grammarAccess.getBTSGraphicAccess().get_idAssignment_3_1(), "rule__BTSGraphic___idAssignment_3_1");
					put(grammarAccess.getBTSGraphicAccess().getInnerSentenceOrderAssignment_4_1(), "rule__BTSGraphic__InnerSentenceOrderAssignment_4_1");
					put(grammarAccess.getBTSGraphicAccess().getCodeAssignment_5_1(), "rule__BTSGraphic__CodeAssignment_5_1");
					put(grammarAccess.getBTSGraphicAccess().getReferenceAssignment_6_1(), "rule__BTSGraphic__ReferenceAssignment_6_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.bbaw.bts.corpus.text.dsl.ui.contentassist.antlr.internal.InternalBTSParser typedParser = (org.bbaw.bts.corpus.text.dsl.ui.contentassist.antlr.internal.InternalBTSParser) parser;
			typedParser.entryRuleBTSTextContent();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public BTSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BTSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
