/*
* generated by Xtext
*/
package org.bbaw.bts.corpus.text.egy.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EgyBtsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/bbaw/bts/corpus/text/egy/dsl/parser/antlr/internal/InternalEgyBts.tokens");
	}
}
