/*
* generated by Xtext
*/
package org.bbaw.bts.corpus.text.egy.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.bbaw.bts.corpus.text.egy.dsl.services.EgyBtsGrammarAccess;

public class EgyBtsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EgyBtsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected org.bbaw.bts.corpus.text.egy.dsl.parser.antlr.internal.InternalEgyBtsParser createParser(XtextTokenStream stream) {
		return new org.bbaw.bts.corpus.text.egy.dsl.parser.antlr.internal.InternalEgyBtsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TextContent";
	}
	
	public EgyBtsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EgyBtsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
