/*
* generated by Xtext
*/
package org.bbaw.bts.corpus.text.egy.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EgyBtsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.bbaw.bts.corpus.text.egy.dsl.ui.internal.EgyBtsActivator.getInstance().getInjector("org.bbaw.bts.corpus.text.egy.dsl.EgyBts");
	}
	
}
