/*
 * generated by Xtext
 */
package org.bbaw.bts.corpus.text.egy.ui.contentassist

import org.bbaw.bts.corpus.text.egy.ui.contentassist.AbstractEgyDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EgyDslProposalProvider extends AbstractEgyDslProposalProvider {
}
